# Generated by Django 4.2.2 on 2023-06-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.IntegerField()),
                ('password', models.CharField(max_length=60)),
                ('confirm', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemName',
        ),
        migrations.DeleteModel(
            name='location',
        ),
    ]
