# Generated by Django 4.2.2 on 2023-06-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_registermodel_delete_itemname_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='confirm',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='password',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='phno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='username',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
